<?php 
	return array( 
	
	"home"=>array(
		"html"=>array(
			"type"=>"html",
			"limit"=>3,
			"offset"=>null,
			),
		"product"=>array(
			"type"=>"product",
			"limit"=>9,
			"offset"=>null,
			),
		"testimonial"=>array(
			"type"=>"testimonial",
			"limit"=>3,
			"offset"=>null,
			),
		
		"post"=>array(
			"type"=>"post",
			"limit"=>4,
			"offset"=>null,
			),
		"gallery"=>array(
			"type"=>"gallery",
			"limit"=>8,
			"offset"=>null,
			),
		"slider"=>array(
			"type"=>"slider",
			"limit"=>3,
			"offset"=>null,
			),
		),
			
	"post"=>array(
		"popular_product"=>array(
			"type"=>"product",
			"limit"=>5,
			"offset"=>null,
			),
		"random_product"=>array(
			"type"=>"product",
			"limit"=>5,
			"offset"=>null,
			),
		"post"=>array(
			"type"=>"post",
			"limit"=>4,
			"offset"=>null,
			),
		),
	"page"=>array(
		"popular_product"=>array(
			"type"=>"product",
			"limit"=>5,
			"offset"=>null,
			),
		"random_product"=>array(
			"type"=>"product",
			"limit"=>5,
			"offset"=>null,
			),
		"post"=>array(
			"type"=>"post",
			"limit"=>4,
			"offset"=>null,
			),
		),
	"product"=>array(
		"popular_product"=>array(
			"type"=>"product",
			"limit"=>5,
			"offset"=>null,
			),
		"random_product"=>array(
			"type"=>"product",
			"limit"=>5,
			"offset"=>null,
			),
		"post"=>array(
			"type"=>"post",
			"limit"=>4,
			"offset"=>null,
			),
		),
	"category"=>array(
		"popular_product"=>array(
			"type"=>"product",
			"limit"=>5,
			"offset"=>null,
			),
		"category_product"=>array(
			"type"=>"product",
			"limit"=>5,
			"offset"=>null,
			),
		"post"=>array(
			"type"=>"post",
			"limit"=>4,
			"offset"=>null,
			),
		),
	"category_product"=>array(
		"popular_product"=>array(
			"type"=>"product",
			"limit"=>5,
			"offset"=>null,
			),
		"category_product"=>array(
			"type"=>"product",
			"limit"=>5,
			"offset"=>null,
			),
		"post"=>array(
			"type"=>"post",
			"limit"=>4,
			"offset"=>null,
			),
		),
	);